FROM tiangolo/uvicorn-gunicorn:python3.8

# 작업디렉토리 설정
WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

# install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN apt-get update && \
    apt-get install curl
RUN cd /code && \ 
    curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | bash -s

# 현재경로에 존재하는 app의 모든 소스파일을 /code/app 경로 이미지에 복사
COPY ./app /code/app

EXPOSE 8000
 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]